// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_next_feed_to_fetch.sql

package database

import (
	"context"
)

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT url FROM feeds
ORDER BY last_fetched_at ASC NULLS FIRST
LIMIT 1
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch)
	var url string
	err := row.Scan(&url)
	return url, err
}
