// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_feed_id_user_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedIds = `-- name: GetFeedIds :one
SELECT id
FROM feeds
WHERE url=$1
`

func (q *Queries) GetFeedIds(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFeedIds, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
