// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_posts_from_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPostsFromUser = `-- name: GetPostsFromUser :many
SELECT
    f.name AS feed_name,
    p.title AS title,
    p.url AS url
FROM posts AS p
INNER JOIN feeds AS f
ON f.id = p.feed_id
INNER JOIN feed_follows AS fol
ON p.feed_id = fol.feed_id
WHERE fol.user_id = $1
ORDER BY published_at DESC
LIMIT $2
`

type GetPostsFromUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

type GetPostsFromUserRow struct {
	FeedName string
	Title    string
	Url      string
}

func (q *Queries) GetPostsFromUser(ctx context.Context, arg GetPostsFromUserParams) ([]GetPostsFromUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsFromUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsFromUserRow
	for rows.Next() {
		var i GetPostsFromUserRow
		if err := rows.Scan(&i.FeedName, &i.Title, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
