// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mark_feed_fetched.sql

package database

import (
	"context"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds
SET updated_at = NOW(), last_fetched_at = NOW()
WHERE url = $1
`

func (q *Queries) MarkFeedFetched(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, url)
	return err
}
